In [ ]:
##Q1.Yes, there is a difference in the data type of variables list_ and array_list.

The list_ variable is a Python list, while the array_list variable is a NumPy array.

To print the data types of both variables, you can use the type() function in Python. Here's the code:



In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [2]:
##Q2.Sure! You can use a for loop to iterate over each element of the list and array and then use the type() function to print the data type of each element. Here's the code:

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
##Q3.Yes, there will be a difference in the data type of the elements present in list_ and array_list when array_list is defined with dtype=int. In this case, the elements in array_list will have a data type of int instead of numpy.str_. Here's the updated code to print the data types of each element in both list_ and array_list:

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))

    ##For the new array_list, the output of the second loop will be:

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [5]:
##Q4.Sure! You can use the shape and size attributes of the numpy array to find its shape and size, respectively. Here's the code:

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find shape of num_array
print("Shape of num_array:", num_array.shape)

# Find size of num_array
print("Size of num_array:", num_array.size)




Shape of num_array: (2, 3)
Size of num_array: 6


In [ ]:
Here, the shape attribute returns a tuple indicating the dimensions of the array. In this case, num_array has 2 rows and 3 columns, so the shape is (2, 3).

The size attribute returns the total number of elements in the array. In this case, num_array has 6 elements, so the size is 6.


In [6]:
##Q5.Sure! You can use the np.zeros function to create a numpy array of 3x3 matrix containing zeros only. Here's the code:

import numpy as np

zero_array = np.zeros(shape=(3, 3))

print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
